name: Continuous Integration

on: [pull_request]

jobs:
  quality:
    name: Quality checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn install

      - name: Run Test
        run: yarn test
