name: Deploy Storybook
on:
  push:
    branches:
      - main

jobs:
  avoid_redundancy:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previus Redundat Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_toke: ${{ github.token }}
  build_and_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Config git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Install dependencies
        run: yarn install

      - name: Build sotrybook
        run: yarn storybook:build

      - name: Publish on gh pages
        run: |
          yarn storybook:deploy:ci
        env:
          GH_TOKEN: ${{ secrets.ATZOMX_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.ATZOMX_TOKEN }}
